import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// Dev: Vite serves the SPA on 5173 and proxies /api to the Bun server (8787),
// so the Gemini API key never reaches the browser. Prod/smoke: the Bun server
// (server/index.ts) serves the built dist/ AND /api on a single port.
const API_PORT = Number(process.env.API_PORT ?? 8787);

export default defineConfig({
  server: {
    port: 5173,
    proxy: {
      "/api": {
        target: `http://127.0.0.1:${API_PORT}`,
        changeOrigin: true,
      },
    },
  },
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      // Static assets that must be in the precache (so the installed shell + its
      // icons load offline). The PNGs are generated by scripts/gen-icons.ts.
      includeAssets: [
        "favicon.svg",
        "icon.svg",
        "icon-192.png",
        "icon-512.png",
        "apple-touch-icon.png",
      ],
      workbox: {
        // App-shell fallback: any offline navigation is served the precached
        // index.html (this is also vite-plugin-pwa's default — set explicitly so a
        // plugin-default change can't silently break offline launch).
        navigateFallback: "index.html",
        // The Gemini proxy must always hit the network — never serve a cached
        // response for /api/*, and never fall navigations back to the shell for it.
        navigateFallbackDenylist: [/^\/api\//],
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.pathname.startsWith("/api/"),
            handler: "NetworkOnly",
          },
        ],
      },
      manifest: {
        name: "Freat — Fridge to Feast",
        short_name: "Freat",
        description: "Snap your fridge, get meal ideas powered by Gemini.",
        theme_color: "#16a34a",
        background_color: "#0b1120",
        display: "standalone",
        start_url: "/",
        icons: [
          // Crisp scalable "any" icon (un-masked contexts).
          {
            src: "/icon.svg",
            sizes: "any",
            type: "image/svg+xml",
            purpose: "any",
          },
          // Dedicated maskable PNGs (full-bleed bg, glyph in the safe zone) so
          // Android's maskable mask never clips the art. Kept separate from "any"
          // — a combined "any maskable" purpose renders the padded art un-masked.
          {
            src: "/icon-192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "maskable",
          },
          {
            src: "/icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
    }),
  ],
});
